language: node_js
node_js:
   - "0.10"
before_install:
  - export PHANTOMJS_BIN=/usr/local/phantomjs/bin/phantomjs
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar -xjf phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - sudo rm -rf /usr/local/phantomjs/bin/phantomjs
  - sudo mv phantomjs /usr/local/phantomjs/bin/phantomjs
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - bundle install
  - bower install
  - grunt prod
notifications:
  email: true
# Taken from:  https://github.com/mdix/es6-babel-browserify-karma-boilerplate/blob/master/.travis.yml#L3

#test
